#!/bin/bash



CPU=$(cat /proc/cpuinfo | grep "model name" | awk -F": " '{ print $2 }' | head -n1)
CPU=$(echo $CPU)
MEM=$(free -gh | grep "^Mem" | awk -F" " '{ print $2 }')
ARCH=$(uname -m)
TITLE="$CPU || $MEM Bellek || $ARCH mimari"

gnuplot <<- EOF
    set term pdf font ",9"
    set output 'performans.pdf'
    set title '$TITLE'
    set xlabel 'Boyut (kB)'
    set ylabel 'Zaman (s)'
    set grid

    set yrange [-1:60]
    set key box
    set key spacing 1.5

    plot "times.txt" using 0:1 with lp lw 2 t "Linked list", "times.txt" using 1:2 with lp lw 2 t "Hash"
EOF
echo "Grafik performans.pdf dosyasina kaydedildi."
#rm -rf times.txt

